[package]

name = "shadowsocks-rust"
version = "0.9.14"
authors = ["Y. T. CHUNG <zonyitoo@gmail.com>"]

[lib]

name = "shadowsocks"

[features]

default = [
    "cipher-aes-cfb",
    "cipher-rc4",

    "cipher-chacha20",
    "cipher-salsa20",

    "enable-udp",
]

cipher-aes-cfb = []
cipher-rc4 = []
cipher-chacha20 = []
cipher-salsa20 = []

enable-udp = []

[[bin]]

name = "sslocal"
path = "src/bin/local.rs"

[[bin]]

name = "ssserver"
path = "src/bin/server.rs"

[[bin]]

name = "socks5-tool"
path = "src/bin/socks5-tool.rs"

[[bin]]

name = "ssurl"
path = "src/bin/ssurl.rs"

[dependencies]
rustc-serialize = "^0.3.15"
log = "^0.3.1"
byteorder = "^0.5.0"
rand = "^0.3.9"
time = "^0.1.32"
clap = "^1.1.6"
qrcode = "^0.1.6"
env_logger = "^0.3.2"
rust-crypto = "^0.2.34"
ip = "1.0.0"
openssl = "^0.7.14"
lru-cache = "0.0.7"
libc = "^0.2.7"

[dependencies.coio]
git = "https://github.com/zonyitoo/coio-rs.git"
branch = "io-timeouts"
