[package]
name = "arch"
version = "0.0.1"
authors = []

[lib]
name = "uu_arch"
path = "arch.rs"

[dependencies.uucore]
path = "../uucore"
default-features = false
features = ["utsname"]

[[bin]]
name = "arch"
path = "main.rs"
